In [85]:
import pandas as pd

In [86]:
df = pd.read_csv("shark_presence_absence_presence_masked_likelihoods_5_variables.csv")

In [87]:
df.head()

catalogNumber  decimalLatitude  decimalLongitude  \
0   2.362010e+11        -23.03220         113.71500   
1   1.752010e+11        -21.90130         113.90150   
2   1.962010e+12          3.46845          72.80718   
3   1.772010e+12        -23.97360          35.51220   
4   2.142010e+11         12.93330         123.53300   

                   eventDate  month  date_year  bathymetry    sst    sss  \
0  2008-05-18 12:00:00+00:00    5.0     2008.0        55.0  24.90  34.86   
1  2009-04-13 12:00:00+00:00    4.0     2009.0        82.0  25.74  34.82   
2  2007-05-24 12:00:00+00:00    5.0     2007.0       165.0  29.03  34.95   
3  2009-02-25 12:00:00+00:00    2.0     2009.0         2.0  25.61  34.86   
4  2007-04-19 12:00:00+00:00    4.0     2007.0        33.0  28.24  32.56   

   shoredistance  ...  presence Chlorophyll_proxy EKE_proxy  Depth_proxy  \
0          10835  ...         1          0.273381  0.007691     0.333518   
1           7200  ...         1          0.254626  0.038560     0.333611   
2           1425  ...         1          0.184779  0.005755     0.334736   
3            585  ...         1          0.259484  0.009518     0.336746   
4            339  ...         1          0.228264  0.012196     0.339216   

   Combined_score  Likelihood_Chl_proxy  Likelihood_EKE_proxy  \
0        0.162589            4 - Likely       1 - Less likely   
1        0.263351          2 - Possible       3 - More likely   
2       -1.247743       1 - Less likely       1 - Less likely   
3        0.260676            4 - Likely       1 - Less likely   
4       -0.481563       1 - Less likely          2 - Possible   

   Likelihood_SST_pref26C Likelihood_Depth_proxy Likelihood_Combined_proxy  
0            2 - Possible        1 - Less likely              2 - Possible  
1         3 - More likely        1 - Less likely           3 - More likely  
2         1 - Less likely        3 - More likely           1 - Less likely  
3         3 - More likely        3 - More likely              2 - Possible  
4         1 - Less likely             4 - Likely           1 - Less likely  

[5 rows x 23 columns]

In [88]:
# Example dataframe


# Keep only the number part
df["Likelihood_Combined_proxy"] = df["Likelihood_Combined_proxy"].str.extract(r"(\d+)").astype(float)

print(df)


       catalogNumber  decimalLatitude  decimalLongitude  \
0       2.362010e+11       -23.032200        113.715000   
1       1.752010e+11       -21.901300        113.901500   
2       1.962010e+12         3.468450         72.807180   
3       1.772010e+12       -23.973600         35.512200   
4       2.142010e+11        12.933300        123.533000   
...              ...              ...               ...   
25219            NaN        45.398832        -53.135070   
25220            NaN        46.258120       -132.930398   
25221            NaN        70.384837        161.086550   
25222            NaN        68.286182        122.527535   
25223            NaN        48.990143        -36.676455   

                       eventDate  month  date_year   bathymetry        sst  \
0      2008-05-18 12:00:00+00:00    5.0     2008.0    55.000000  24.900000   
1      2009-04-13 12:00:00+00:00    4.0     2009.0    82.000000  25.740000   
2      2007-05-24 12:00:00+00:00    5.0     2007.0   165.

In [89]:
df = df.dropna(how="all")


In [90]:
df.shape

(25224, 23)

In [91]:
df.columns

Index(['catalogNumber', 'decimalLatitude', 'decimalLongitude', 'eventDate',
       'month', 'date_year', 'bathymetry', 'sst', 'sss', 'shoredistance',
       'behavior', 'sex', 'id', 'presence', 'Chlorophyll_proxy', 'EKE_proxy',
       'Depth_proxy', 'Combined_score', 'Likelihood_Chl_proxy',
       'Likelihood_EKE_proxy', 'Likelihood_SST_pref26C',
       'Likelihood_Depth_proxy', 'Likelihood_Combined_proxy'],
      dtype='object')

In [92]:
df = df.drop(
    ["Likelihood_Chl_proxy", 
     "Likelihood_EKE_proxy", 
     "Likelihood_SST_pref26C", 
     "Likelihood_Depth_proxy"], 
    axis=1
)


In [93]:
df.shape

(25224, 19)

In [94]:
df = df.fillna(df.mean(numeric_only=True))


In [95]:
df.dropna()

Empty DataFrame
Columns: [catalogNumber, decimalLatitude, decimalLongitude, eventDate, month, date_year, bathymetry, sst, sss, shoredistance, behavior, sex, id, presence, Chlorophyll_proxy, EKE_proxy, Depth_proxy, Combined_score, Likelihood_Combined_proxy]
Index: []

In [96]:
df.shape

(25224, 19)

In [97]:
df.drop("id", axis=1)

catalogNumber  decimalLatitude  decimalLongitude  \
0       2.362010e+11       -23.032200        113.715000   
1       1.752010e+11       -21.901300        113.901500   
2       1.962010e+12         3.468450         72.807180   
3       1.772010e+12       -23.973600         35.512200   
4       2.142010e+11        12.933300        123.533000   
...              ...              ...               ...   
25219   1.330290e+12        45.398832        -53.135070   
25220   1.330290e+12        46.258120       -132.930398   
25221   1.330290e+12        70.384837        161.086550   
25222   1.330290e+12        68.286182        122.527535   
25223   1.330290e+12        48.990143        -36.676455   

                       eventDate  month  date_year   bathymetry        sst  \
0      2008-05-18 12:00:00+00:00    5.0     2008.0    55.000000  24.900000   
1      2009-04-13 12:00:00+00:00    4.0     2009.0    82.000000  25.740000   
2      2007-05-24 12:00:00+00:00    5.0     2007.0   165.000000  29.030000   
3      2009-02-25 12:00:00+00:00    2.0     2009.0     2.000000  25.610000   
4      2007-04-19 12:00:00+00:00    4.0     2007.0    33.000000  28.240000   
...                          ...    ...        ...          ...        ...   
25219             Pseudo-Absence   12.0     1998.0  2449.229677  -0.920632   
25220             Pseudo-Absence    4.0     1983.0  3467.185071   1.470310   
25221             Pseudo-Absence    5.0     1992.0  2030.210218  -1.866610   
25222             Pseudo-Absence    4.0     2001.0  3114.714077  63.582033   
25223             Pseudo-Absence   10.0     2002.0  5321.465320  57.690487   

             sss  shoredistance  behavior     sex  presence  \
0      34.860000          10835       NaN     NaN         1   
1      34.820000           7200       NaN     NaN         1   
2      34.950000           1425       NaN     NaN         1   
3      34.860000            585       NaN    male         1   
4      32.560000            339       NaN  female         1   
...          ...            ...       ...     ...       ...   
25219   8.488361           1606       NaN     NaN         0   
25220  47.356076           5370       NaN     NaN         0   
25221  47.376300           5139       NaN     NaN         0   
25222  51.615286           1539       NaN     NaN         0   
25223   4.448084           4780       NaN     NaN         0   

       Chlorophyll_proxy  EKE_proxy  Depth_proxy  Combined_score  \
0               0.273381   0.007691     0.333518    1.625886e-01   
1               0.254626   0.038560     0.333611    2.633510e-01   
2               0.184779   0.005755     0.334736   -1.247743e+00   
3               0.259484   0.009518     0.336746    2.606756e-01   
4               0.228264   0.012196     0.339216   -4.815633e-01   
...                  ...        ...          ...             ...   
25219           0.247200   0.037693     0.335614   -5.049349e-17   
25220           0.247200   0.037693     0.335614   -5.049349e-17   
25221           0.247200   0.037693     0.335614   -5.049349e-17   
25222           0.247200   0.037693     0.335614   -5.049349e-17   
25223           0.247200   0.037693     0.335614   -5.049349e-17   

       Likelihood_Combined_proxy  
0                       2.000000  
1                       3.000000  
2                       1.000000  
3                       2.000000  
4                       1.000000  
...                          ...  
25219                   2.236204  
25220                   2.236204  
25221                   2.236204  
25222                   2.236204  
25223                   2.236204  

[25224 rows x 18 columns]

In [98]:
df.loc[df["presence"] == 0, "Likelihood_Combined_proxy"] = 0

In [99]:
df.head()

catalogNumber  decimalLatitude  decimalLongitude  \
0   2.362010e+11        -23.03220         113.71500   
1   1.752010e+11        -21.90130         113.90150   
2   1.962010e+12          3.46845          72.80718   
3   1.772010e+12        -23.97360          35.51220   
4   2.142010e+11         12.93330         123.53300   

                   eventDate  month  date_year  bathymetry    sst    sss  \
0  2008-05-18 12:00:00+00:00    5.0     2008.0        55.0  24.90  34.86   
1  2009-04-13 12:00:00+00:00    4.0     2009.0        82.0  25.74  34.82   
2  2007-05-24 12:00:00+00:00    5.0     2007.0       165.0  29.03  34.95   
3  2009-02-25 12:00:00+00:00    2.0     2009.0         2.0  25.61  34.86   
4  2007-04-19 12:00:00+00:00    4.0     2007.0        33.0  28.24  32.56   

   shoredistance  behavior     sex                                    id  \
0          10835       NaN     NaN  e8a96329-cc06-4f16-a546-9a41c8eabdaf   
1           7200       NaN     NaN  35af271b-d876-4de5-9744-eb3cd639acea   
2           1425       NaN     NaN  d4e014f1-5dcf-493c-bbd9-cfa48291f63f   
3            585       NaN    male  05c794e3-6547-4307-b201-bb71c1151c79   
4            339       NaN  female  055e9228-d4ca-4e3f-9cbd-61913fcbf272   

   presence  Chlorophyll_proxy  EKE_proxy  Depth_proxy  Combined_score  \
0         1           0.273381   0.007691     0.333518        0.162589   
1         1           0.254626   0.038560     0.333611        0.263351   
2         1           0.184779   0.005755     0.334736       -1.247743   
3         1           0.259484   0.009518     0.336746        0.260676   
4         1           0.228264   0.012196     0.339216       -0.481563   

   Likelihood_Combined_proxy  
0                        2.0  
1                        3.0  
2                        1.0  
3                        2.0  
4                        1.0

In [100]:
df.to_csv("likelyhood_prediction_data_ready_to_train_v2.csv", index=True)

In [101]:
# Features
X = df[[
    "decimalLatitude", 
    "decimalLongitude", 
    "month", 
    "bathymetry", 
    "sst", 
    "sss", 
    "shoredistance"
]]

# Target
y = df["Likelihood_Combined_proxy"]


In [102]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


## Model Training

In [103]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [111]:
model = XGBClassifier(
    objective='multi:softmax',  # softmax gives predicted class directly
    num_class=5,
    eval_metric='mlogloss',  # recommended for multiclass
    use_label_encoder=False,
    n_estimators=100,
    learning_rate=0.1,
    max_depth=6,
    random_state=42
)



In [105]:
model.fit(X_train, y_train)


C:\Users\Shubham Prajapati.LAPTOP-OVUQKEGP\AppData\Roaming\Python\Python313\site-packages\xgboost\training.py:183: UserWarning: [11:30:14] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None, num_class=5, ...)

In [106]:
y_pred = model.predict(X_test)


In [107]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


Accuracy: 0.9938553022794846

Classification Report:
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      3326
         1.0       0.99      1.00      0.99       555
         2.0       0.99      0.96      0.97       402
         3.0       1.00      1.00      1.00       554
         4.0       0.94      0.97      0.95       208

    accuracy                           0.99      5045
   macro avg       0.98      0.98      0.98      5045
weighted avg       0.99      0.99      0.99      5045


Confusion Matrix:
 [[3323    2    0    0    1]
 [   2  553    0    0    0]
 [   3    4  384    0   11]
 [   0    0    0  552    2]
 [   2    1    2    1  202]]


## Test cases

In [112]:
import pandas as pd

# --- Define 25 Test Cases --- (keep as before)
test_cases = [
    {"decimalLatitude": 20.0, "decimalLongitude": -80.0, "month": 6, "bathymetry": 500, "sst": 28.5, "sss": 35.0, "shoredistance": 150, "case_name": "Caribbean Habitat"},
    {"decimalLatitude": 0.0, "decimalLongitude": -15.0, "month": 12, "bathymetry": 4000, "sst": 27.0, "sss": 34.5, "shoredistance": 2500, "case_name": "Central Atlantic"},
    # ... keep all other 23 cases ...
]

# --- Expected outputs (5-class, adjust as needed) ---
expected_outputs = [
    4,0,0,0,0,0,0,1,2,0,0,0,3,2,3,   # example mapping for original 15
    3,2,0,2,3,0,2,3,0,4               # example mapping for new 10
]

# --- Convert to DataFrame for prediction ---
df_test = pd.DataFrame(test_cases).drop(columns=["case_name"])


# Make sure length matches
if len(df_test) != len(expected_outputs):
    raise ValueError(f"Length mismatch: df_test has {len(df_test)} rows, expected_outputs has {len(expected_outputs)} values")

# Run predictions
predictions = model.predict(df_test)

# Compare results
df_results = pd.DataFrame(test_cases)
df_results["prediction"] = predictions
df_results["expected"] = expected_outputs
df_results["result"] = df_results["prediction"] == df_results["expected"]

print(df_results[["case_name", "expected", "prediction", "result"]])
print(f"\nTest Summary: {df_results['result'].sum()}/{len(df_results)} tests passed.")


ValueError: Length mismatch: df_test has 2 rows, expected_outputs has 25 values